#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BACKPORT_BUILD_CORDIC_MODULE 1
#define CPTCFG_BACKPORT_USERSEL_BUILD_ALL 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_NL80211_TESTMODE 1
#define CPTCFG_CFG80211_DEFAULT_PS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_INTERNAL_REGDB 1
#define CPTCFG_CFG80211_WEXT 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
